name: Aegis CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          uv sync

      - name: Ruff
        run: |
          uv run ruff check .

      - name: MyPy
        run: |
          uv run mypy services

      - name: Pytest
        run: |
          uv run pytest


# In local dev machine, we can to these validations manually:
# uv run ruff check . # Check code quality with Ruff
# uv run ruff check . --fix # Automatically fix code quality issues with Ruff
# uv run mypy services # Check type hints with MyPy
# uv run pytest # Run tests with Pytest
# uv run python -m scripts.smoke_test_agent # Run smoke test for the agent
# uv run python -m scripts.smoke_test_tools # Run smoke test for the tools
